### ISSUE TITLE
Build and install Apple Silicon-targeted versions of vendir

### ISSUE THREAD

**Issue by pivotaljohn** [carvel-dev/vendir#100]
see vmware-tanzu/carvel#218

Do it like we do for ytt.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by benmoss** [comment]
What's the release process for this repo? I see [imgpkg uses GoReleaser](https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/.goreleaser.yml), but it seems we don't

**Comment by danielhelfand** [comment]
> What's the release process for this repo?

It's currently a manual process: 1. Bump the version constant used 2. Create a tag for the release. 3. Locally, run `./hack/build-binaries.sh` 4. Upload the binaries to a GitHub release through the UI 5. Write release notes

There is an open pr for automating in a similar way to imgpkg: #108. However, there are also some thoughts about moving away from goreleaser for Carvel releases as well.

**Comment by cppforlife** [comment]
i think this is resolved since we have vendir-darwin-arm64
