### ISSUE TITLE
Git errors occurring during the vendir-temp step, resulting in inability to troubleshoot

### ISSUE THREAD

**Issue by ScriptAutomate** [carvel-dev/vendir#105]
**What steps did you take:**

When working with the following repo:
- https://gitlab.com/saltstack/open/docs/salt-user-guide

```bash
git clone git@gitlab.com:saltstack/open/docs/salt-user-guide.git
git checkout -b testing
pre-commit install
pre-commit run --all # Works without errors

# vendir sync works normally
vendir sync

# Make modification to file
vim docs/requirements.txt # Example: Update sphinx version
git commit -m "Updating sphinx"

# Error occurs in pre-commit call
```

I have also tried setting up a fresh repo, and _not_ running `vendir sync` first. The `pre-commit` step still borks out.

**What happened:**

Output during `pre-commit` usage:

```
...
...
vale-styles..............................................................Failed
- hook id: vendir
- exit code: 1

Fetching: .vale/styles + Google (git from https://github.com/errata-ai/Google@v0.3.3)

  --> git init
  Initialized empty Git repository in /home/dscripter/git/saltopen/salt-user-guide/.vendir-tmp/incoming/git/.git/
  --> git config credential.helper store --file /home/dscripter/git/saltopen/salt-user-guide/.vendir-tmp/incoming/git-auth/.git-credentials
  --> git remote add origin https://github.com/errata-ai/Google
  --> git config remote.origin.tagOpt --tags
  --> git fetch origin
  From https://github.com/errata-ai/Google
   * [new branch]      master     -> origin/master
   * [new tag]         v0.1.0     -> v0.1.0
   * [new tag]         v0.1.1     -> v0.1.1
   * [new tag]         v0.2.0     -> v0.2.0
   * [new tag]         v0.3.0     -> v0.3.0
   * [new tag]         v0.3.1     -> v0.3.1
   * [new tag]         v0.3.2     -> v0.3.2
   * [new tag]         v0.3.3     -> v0.3.3
  --> git -c advice.detachedHead=false checkout v0.3.3
  error: Your local changes to the following files would be overwritten by checkout:
  	.gitignore
  	LICENSE
  Please commit your changes or stash them before you switch branches.
  Aborting

vendir: Error: Syncing directory '.vale/styles':
  Syncing directory 'Google' with git contents:
    Fetching git repository:
      Git [-c advice.detachedHead=false checkout v0.3.3]: exit status 1 (stderr: error: Your local changes to the following files would be overwritten by checkout:
	.gitignore
	LICENSE
Please commit your changes or stash them before you switch branches.
Aborting
)
...
```

How [`pre-commit`](https://pre-commit.com/) config calls to `vendir` are done:

```yaml
  - repo: local
    hooks:
      - id: vendir
        name: vale-styles
        description: Pull down vale styles.
        entry: vendir sync
        language: system
        always_run: true
        pass_filenames: false
```

**What did you expect:**
[A description of what was expected]

I expected it to sync without issue, or for `vendir` to have some kind of verbose or debug output to understand where/why/how the error is occurring. It looks like some modification is happening to files upon bringing them down, preventing a checkout from occurring. **I'm wondering whether there could be some kind of `git` cleaning/stashing (with drop), etc. that could be done before a checkout, in order to override whatever changes are preventing a checkout from occurring when `vendir` is doing work in `vendir-temp`?** It's difficult to troubleshoot, and I'm not sure where to start since I can replicate this on two Pop!_OS systems, but not within clean Ubuntu containers, leading me to think some slight configuration somewhere is leading to the weird `git` behavior, but hard to know.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- vendir version (execute `vendir --version`):

```
$ vendir --version
vendir version 0.22.0
```

- OS (e.g. from `/etc/os-release`):

```bash
$ cat /etc/*ease*
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Pop!_OS"
VERSION="20.04 LTS"
...
...
```

- git version

```
$ git --version
git version 2.25.1
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
@ScriptAutomate i cannot reproduce above. im guessing this is somehow related to your system setup. can you try reproducing this problem in a container or a vm to see if it still happens for you?

**Comment by cppforlife** [comment]
feel free to reopen if more info can be provided.
