### ISSUE TITLE
Support extracting username/password from base64 string under auth key for dockerconfigjson secrets

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/vendir#106]
**Describe the problem/challenge you have**

As outlined in https://github.com/vmware-tanzu/carvel-kapp-controller/issues/360, vendir should support extracting username/password as base64 encoded string under the auth key of a Kubernetes secret of dockerconfigjson. 

Currently, only username/password are supported:

```json
{
            "auths": {
                    "<HOSTNAME:PORT>": {
                        "username": "testuser",
                        "password": "testpassword"
                    }
            }
    }
```

**Describe the solution you'd like**

vendir should support the following format for Kubernetes secrets of type dockerconfigjson:

```json
{
        "auths": {
                "<HOSTNAME:PORT>": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                }
        }
}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
being addressed in https://github.com/vmware-tanzu/carvel-vendir/pull/107

**Comment by cppforlife** [comment]
included in https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.23.0
