### ISSUE TITLE
🐦 Please tweet about the v0.23.0 release 🐦 

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#109]
Hi guys,

could you tweet about this latest release please ? 😺 

https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.23.0

Thanks in advance.

Have a nice week-end
Kind Regards,

Adrien

**Comment by adriens** [comment]
https://github.com/adriens/chocolatey-vendir/issues/13

**Comment by DennisDenuto** [comment]
cc @microwavables

**Comment by microwavables** [comment]
@adriens done! https://twitter.com/carvel_dev/status/1440361189104447492?s=20

**Comment by adriens** [comment]
Yop @microwavables : RT 👍 https://twitter.com/rastadidi/status/1440421396652249094
