### ISSUE TITLE
Feature Request: Allow sync (or bumps) for specific dependencies

### ISSUE THREAD

**Issue by ciriarte** [carvel-dev/vendir#11]
# Context

**vendir** currently supports the `--directory` flag:

```console
$ vendir sync -d my_dependency
```

But it doesn't save the lock file. I would like vendir to be able to isolate sync/bumps to a specific dependency.

**Comment by cari-lynn** [comment]
Hey @ciriarte!
Let us know if this captures your intent.

Currently `vendir sync` only syncs an entire vendir.yml file.
You can use `vendir sync --directory` to override contents of particular directories by pointing them to local directories. However, this does not update the lock file.

To support syncing only a subset of the dependencies in the vendir.yml, vendir sync would provide the ability to target the given dependencies, and update the vendir.lock.yml with the new metadata.

**Comment by cppforlife** [comment]
@ciriarte we wouldnt expect to modify anything other dependencies -- even if they were modified on disk, intentionally or unintentionally -- right?

**Comment by ciriarte** [comment]
> @ciriarte we wouldnt expect to modify anything other dependencies -- even if they were modified on disk, intentionally or unintentionally -- right?

My expectation is that vendir will only update the directory it is managing and I've instructed in the `vendir sync -d some_dir` call.

**Comment by ciriarte** [comment]
> Currently `vendir sync` only syncs an entire vendir.yml file.
> You can use `vendir sync --directory` to override contents of particular directories by pointing them to local directories. However, this does not update the lock file.

@pivotal-dean

My understanding is that `vendir sync -d` has a couple of options per the help command:

1. It does sync local dirs if used with `dir/sub-dir[=local-dir]` **I'm not really interested in this workflow at the moment** 🚫 
2. It synchronizes with a remote if the optional `[=local-dir]` is omitted. **This does something close to my desired outcome** ✅ 

If my understanding of 2 is correct, then you captured my wishes perfectly in the following sentence:

> To support syncing only a subset of the dependencies in the vendir.yml, vendir sync would provide the ability to target the given dependencies, and update the vendir.lock.yml with the new metadata.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/vendir/releases/tag/v0.10.0
