### ISSUE TITLE
When tests fail examples/ gets polluted (currently intentional)

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/vendir#126]
I was running the tests e2e test TestExamplesDir from the IDE or all tests using `hack/test-e2e.sh` and when the `hg` example test failed this is what the git repository looked like:

<img width="601" alt="Screen Shot 2021-12-23 at 11 19 34 AM" src="https://user-images.githubusercontent.com/1826130/147273236-255cca19-3cba-4534-9414-529e326aeebb.png">

The e2e tests should avoid changing the code's git repository.

**Comment by cppforlife** [comment]
behaviour is currently intentional. it was the easiest to implement. open to ideas how to improve it as a PR.
