### ISSUE TITLE
Is a Windows version of vendir available?

### ISSUE THREAD

**Issue by frizzr** [carvel-dev/vendir#127]
Although you list having a windows version of vendir, when you go to download it from the Releases page, it always fails with a 403 Forbidden.

Is it just not available or is this just a bug in your releases page?

**Comment by cppforlife** [comment]
i just clicked on the link from https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.24.0 and downloaded successfully. may be there were some github outages -- not sure?

**Comment by frizzr** [comment]
I'll close this for now. I believe this could be a proxy/VPN issue at our company. It works from our office but not remotely.
