### ISSUE TITLE
hg example requires a lot of maintenance due to using main branch of repository

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/vendir#128]
The [hg example](https://github.com/vmware-tanzu/carvel-vendir/tree/3200f3fb11c2ee657a79516b0f1046b83d4bc44f/examples/hg) regularly needs to be updated since it uses the default branch of this source hut repository: https://hg.sr.ht/~sircmpwn/hg.sr.ht. This can be confusing for contributors/maintainers to vendir.

CI fails frequently since the latest commit and sha change for the default branch often. The example uses a [vendir.lock.yml](https://github.com/vmware-tanzu/carvel-vendir/blob/3200f3fb11c2ee657a79516b0f1046b83d4bc44f/examples/hg/vendir.lock.yml#L12) to assert on the correct assets being pulled. Since the branch changes frequently, it fails often. An example of this is shown in the CI logs of #125: https://github.com/vmware-tanzu/carvel-vendir/runs/4620111721?check_suite_focus=true

Is there a better pattern that can be used to test the branch fetching for this example? It does not seem the repository used in this example has stable branches to use.

**Comment by cppforlife** [comment]
closed via above PR.
