### ISSUE TITLE
vendir fails when target path does not exist

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/vendir#13]
```
Error: Syncing directory 'vendor/k8s': Moving staging directory '.vendir-tmp/staging' to final location 'vendor/k8s': rename .vendir-tmp/staging vendor/k8s: no such file or directory
```

That `vendir/k8s` directory does not exist, and vendir should probably create it as long as it's relative to the current path.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/vendir/commit/95e33e631622149ce90163ca93ae8a5d5a4c4ae4. will be included in next release.

**Comment by jorgemoralespou** [comment]
@cppforlife has this been released?

**Comment by cppforlife** [comment]
> @cppforlife has this been released?

not yet. one way to tell if commit is in a release is to click on commit and see if it's under any tags (aside from develop branch).

**Comment by cppforlife** [comment]
included in https://github.com/k14s/vendir/releases/tag/v0.10.0

**Comment by NexZhu** [comment]
This is still happenning with 0.19.0 on Windows
```
?[31mError: Syncing directory 'manage': Moving staging directory '.vendir-tmp\staging' to final location 'manage': rename .vendir-tmp\staging manage: Access is denied.?[0m
```

**Comment by NexZhu** [comment]
@cppforlife Can you reopen the issue?
