### ISSUE TITLE
🐦 Please tweet about v0.26.0

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#142]
So I can RT it for https://github.com/adriens/chocolatey-vendir/issues/16 🙏

**Comment by adriens** [comment]
Tweets cf https://twitter.com/rastadidi/status/1503469567942692864

**Comment by microwavables** [comment]
Sorry @adriens I was OOO since Thursday. Thanks!

**Comment by adriens** [comment]
No worries @microwavables 💟
