### ISSUE TITLE
Create linux-arm64 binaries

### ISSUE THREAD

**Issue by joshrosso** [carvel-dev/vendir#143]
For linux-arm users along with supporting:

* https://github.com/vmware-tanzu/carvel-kapp-controller/issues/573

**Comment by benmoss** [comment]
It looks like we already have linux-arm64 releases for this repo
<img width="862" alt="Screen Shot 2022-03-15 at 11 28 58 AM" src="https://user-images.githubusercontent.com/239754/158412964-54f4136c-e501-44eb-adb3-7ef281438b99.png">

**Comment by joshrosso** [comment]
oops, ty.
