### ISSUE TITLE
Unpacking imgpkg image and bundle should restore group/other. 

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/vendir#149]
**Describe the problem/challenge you have**

When using `image` and `impkgBundle`, want unpacked files to have group/other permissions restored, with umask applied as appropriate if using owner permissions.

**Describe the solution you'd like**

Want changes made to support:

* https://github.com/vmware-tanzu/carvel-imgpkg/issues/349

applied to `vendir` usage as well.

If `vendir` runs `imgpkg` command line binary then would get it automatically. If however it includes go lang code, then needs to ensure it is using updated code from `imgpkg`.

**Anything else you would like to add:**

Nope.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
per discussion in [OSS slack](https://kubernetes.slack.com/archives/CH8KCCKA5/p1649825240800169), this should be fixed by imgpkg changes alone.
