### ISSUE TITLE
If set legalPaths explicitly to empty list that should override defaults.

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/vendir#151]
**What steps did you take:**

Set:

```
    legalPaths: []
```

Then set other rules to ensure that a `LICENSE` file shouldn't be included. Eg.,

```
    includePaths:
    - /workshop/**
    - /exercises/**
```

or:

```
    excludePaths:
    - LICENSE
```

**What happened:**

The `LICENSE` file was still included.

**What did you expect:**

It seems that `vendir` does not distinguish between `licensePaths` being unset (ie., null) and being set to an empty list.

If `licensePaths` is not set then it is fair to use the builtin defaults. If however it is explicitly set to an empty list, then that should override the builtin defaults.

**Anything else you would like to add:**

Nope.

**Environment:**

```
vendir version 0.24.0
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
thanks @GrahamDumpleton
