### ISSUE TITLE
:bird:  Please Tweet about v0.27.0 release :pray: 

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#156]
Hi, could you please tweet about [v0.27.0](https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.27.0) so I can RT it cf https://github.com/adriens/chocolatey-vendir/issues/17 :grey_question:

**Comment by adriens** [comment]
Hi guys, any chance to have a Tweet :pray: :grey_question:

**Comment by neil-hickey** [comment]
thanks for the prompt @adriens ! We went ahead and tweeted:

https://twitter.com/carvel_dev/status/1522278250327818240?s=20&t=_YeTd3n8j_5tOpU33XmYhg

**Comment by microwavables** [comment]
@adriens feel free to tag me directly if I miss a tweet! :)

**Comment by adriens** [comment]
:ok_hand: , just RT it https://twitter.com/rastadidi/status/1522317063326339072 :smile_cat:
