### ISSUE TITLE
v0.27.0 artifacts missing checksums.txt

### ISSUE THREAD

**Issue by andrewrothstein** [carvel-dev/vendir#158]
**What steps did you take:**
Look here: https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.27.0

**What happened:**
checksums.txt missing

**What did you expect:**
A checksums.txt file

**Anything else you would like to add:**
Build looks like it uploaded it here: https://github.com/vmware-tanzu/carvel-vendir/runs/6217727740?check_suite_focus=true#step:4:241

**Environment:**

- vendir version (execute `vendir --version`):
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Fixed it by adding to the release the missing checksums file.
