### ISSUE TITLE
Publish `v0.30.0` through the Carvel Homebrew tap

### ISSUE THREAD

**Issue by mamachanko** [carvel-dev/vendir#179]
[vmware-tanzu/homebrew-carvel](https://github.com/vmware-tanzu/homebrew-carvel) contains `v.0.29.0`

**Comment by joaopapereira** [comment]
Jun rerun the release automation, vendir should be updated on all fronts.
Feel free to reopen if that is not the case

**Comment by mamachanko** [comment]
@joaopapereira it works! ❤️ `vendir`
