### ISSUE TITLE
Expected directory contents type to be specified (one of git, manual, etc.)

### ISSUE THREAD

**Issue by kvaps** [carvel-dev/vendir#18]
Hi, could you please clarify what exactly should be specified, and where?

to reproduce:
```
git clone https://github.com/k14s/vendir
cd vendir/examples/image
vendir sync
```

output:
```
Error: Validating config: Validating directory 'vendor' (0): Validating directory contents 'docker.io/dkalinin/consul-helm-naked' (0): Expected directory contents type to be specified (one of git, manual, etc.)
```

**Comment by cppforlife** [comment]
@kvaps we have not cut a release yet that includes several source types (image, helm, etc.). currently working on a few additional bits before making 0.11.0.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/vendir/releases/tag/v0.11.0
