### ISSUE TITLE
Typo in project's tags > "vendor" instead of "vendir

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#27]
Hi, there's a minor typo in the projects tags: `vendor` instead of `vendir`

![image](https://user-images.githubusercontent.com/5235127/99867683-a8058e00-2c0f-11eb-9792-cb7762022240.png)

**Comment by danielhelfand** [comment]
I think the tag is more about the general concept of vendoring as described in the description. No other Carvel repos have a tag with the project name.
