### ISSUE TITLE
Only run sync for stable versions, if vendir.yaml has changed since last sync

### ISSUE THREAD

**Issue by fritzduchardt** [carvel-dev/vendir#278]
**Describe the problem/challenge you have**

We have a rollout mechanism that heavily relies on vendir to pull in upstream workloads from Helm Charts, OCI Images and Git Repositories. Most of these workloads have fixed versions and don't change unless their corresponding vendir.yaml is modified. Yet, currently vendir constrains us to sync everything on every run, which slows down the process unnecessarily.

**Describe the solution you'd like**

We would benefit from a feature that runs sync only, if the vendir.yaml was changed after the last sync.  We would activate this feature for all workloads with stable versions.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by kumaritanushree** [comment]
@fritzduchardt isn't it similar to this issue https://github.com/carvel-dev/vendir/issues/274#issuecomment-1689082794 ? Any specific reason for having two separate issues?

**Comment by fritzduchardt** [comment]
Hi @kumaritanushree, it is referring to the same issue, I accidentally created it twice - sorry about that. Shall we close #274

**Comment by kumaritanushree** [comment]
@fritzduchardt sure, add this issue link there and mention the reason and can close #274 
Thank you
