### ISSUE TITLE
New source idea > java artefacts (ie. java dependencies)

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#28]
Hi, I wonder it would not be useful to be able to pick jar java artifacts (aka. maven/gradle dependencies).

We could target:

- [ ] maven central
- [ ] jitpack
- [ ] any private JFrog artifactory or Nexus repo

**Comment by cppforlife** [comment]
@adriens sounds interesting. tell us more about what you thinking? (im not too familiar with java world workflows)

**Comment by adriens** [comment]
Sorry for late anwser @cppforlife .

Then, by being able to reference a Java artifact [thanks to a repo](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.18) then classical artefact properties:, please find below PostgreSQL jdbc driver : 
```xml
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.2.18</version>
</dependency>
```

you get the garanty that you have a get certified jar.

This could be useful if people may like to add jars to their directory, and get the proof of where the jar comes from (vs. manually have to put it in the directory).

For [Spring Boot](https://spring.io/projects/spring-boot) applications, the container often is a single jar, with configuration and certificates.

In that case, that could be very interesting, I guess, if I did really did good understant the purpose of `vendir`

Please, in any case, let me know so I'll learn more about the tool. 🙏

**Comment by cppforlife** [comment]
that sounds like a bit closer to what typical lang-specific dependency manager is doing (eg maven). of course vendir could add a source that would use maven but id like to see a bit more concrete proposal there. (eg what does it look like, what maven command we would be running, etc.)

> This could be useful if people may like to add jars to their directory, and get the proof of where the jar comes from (vs. manually have to put it in the directory).

if you are grabbing random jars from somewhere, then you can definitely codify that with vendir via one of the existing methods like http download.

> if I did really did good understand the purpose of vendir

purpose of vendir is to populate directory based on a config and remove old subdirectories/files that are not longer needed. you can compare it to more generic git submodule.

**Comment by adriens** [comment]
> then you can definitely codify that with vendir via one of the existing methods like http download

Sure, definitely 👍 Hence it would not look like a java rtefect buth rather like any other `http` resource, but without specific java artefact configuration.

So, I 'm dropping this feature request 👍
