### ISSUE TITLE
https://kubernetes-charts.storage.googleapis.com/ has been Removed

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/vendir#38]
[Tests are failing](https://github.com/vmware-tanzu/carvel-vendir/runs/1664182562) due to the removal of https://kubernetes-charts.storage.googleapis.com/. 

The url is hardcoded in vendir [here](https://github.com/vmware-tanzu/carvel-vendir/blob/f5dc883e5e199774786b79c2e9557b2949f1a16e/pkg/vendir/fetch/helmchart/sync.go#L131).

**Comment by ewrenn8** [comment]
Bumped the helm binary used in the tests to the version where the hardcoded url was removed (v2.17.0) here 7930bc2272a07497b3a8d5d7144071d310fc36a2. If users run in to this problem, they will need to update the helm binary on their system to a version without the url as well.
