### ISSUE TITLE
Support Helm 3 OCI Charts

### ISSUE THREAD

**Issue by voor** [carvel-dev/vendir#59]
**Describe the problem/challenge you have**
I would like to relocate a Helm chart that is stored in an experimental OCI image

Additional troubleshooting: https://kubernetes.slack.com/archives/CH8KCCKA5/p1618514640321100

**Describe the solution you'd like**
The helm chart is inside the container image, but it has an invalid rootfs so is failing on image pull, no preference on whether that means it's `helmChart` `imgpkgBundle` `image` or even `http`

**Anything else you would like to add:**

**Comment by cppforlife** [comment]
included in https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.19.0. will be included in kapp-controller shortly.
