### ISSUE TITLE
Looks like `vendir-windows-amd64.exe` of v0.19.0 returns `0.18.0` (instead of `0.19.0`)

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#61]
**What steps did you take:**

1. Download `vendir-windows-amd64.exe` binary from https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.19.0
2. Run `vendir-windows-amd64.exe version`
3. Check that it answers : `0.18.0` (instead of `0.19.0`)

**What happened:**

- It answers : `0.18.0` instead of `0.19.0`

**What did you expect:**

- Should answer `0.19.0`

**Environment:**

- OS (e.g. from `/etc/os-release`): `Windows`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by ewrenn8** [comment]
Thanks for the heads up, looks like they may have been built before the version was bumped. I will upload new assets right now

**Comment by adriens** [comment]
Yep, as I've checked the source code and the version is the good one 👍

**Comment by adriens** [comment]
Just let me know when you have dropped the asset, I'll confirm you the fix

**Comment by ewrenn8** [comment]
Its been uploaded

**Comment by adriens** [comment]
I'm giving it a try now

**Comment by adriens** [comment]
I'm giving it a try now

**Comment by adriens** [comment]
```
vendir-windows-amd64.exe version
vendir version 0.19.0

Succeeded
```
