### ISSUE TITLE
vendir sync -l -d some_path doesn't filter by some_path

### ISSUE THREAD

**Issue by ciriarte** [carvel-dev/vendir#72]
**What steps did you take:**

```
vendir sync -l -d somepath
```

**What happened:**

I invoked vendir with `-l` and `-d some_path` and it downloaded all the artifacts in the lockfile, instead of just the locked dependency I was specifying.

**What did you expect:**

I was expecting to fetch only the directory specified by `-d some_path`

**Anything else you would like to add:**

Not really.

**Environment:**

- vendir version 0.13.0
- Ubuntu 20.04.2.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
hmm, can you provide a little example. im not sure -l and -d were implemented to work together at this point. (at least im getting an error: `Error: Expected to find directory 'vendor/docker.io/ewrenn/consul-helm-naked' within lock config, but did not` when using it.)
