### ISSUE TITLE
🚀 No tweet that announces the v0.20.0 release

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#78]
Hi, I use the [release](https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.20.0) tweet to communicate on the choco package availabiliy, but this time I just can't find the related tweet : can you do one as usual please ?

Thanks in advance for your help.
Friendly yours,
Adrien

**Comment by ewrenn8** [comment]
Sorry about that! I've let the folks responsible for the twitter know and will update you once the tweet has been posted.

**Comment by adriens** [comment]
Yes, that's great. In the mean time, I'm waiting on choco review phase that can take some days sometimes...
Thanks a lot for your comment 👍

**Comment by adriens** [comment]
https://www.linkedin.com/posts/adrien-sales_carvel-vendir-0200-activity-6813643788041486336-SkTq

**Comment by adriens** [comment]
https://community.chocolatey.org/packages/vendir/0.20.0

**Comment by adriens** [comment]
Ready to retweet your release Tweet

**Comment by microwavables** [comment]
> Ready to retweet your release Tweet

@adriens Here ya go! https://twitter.com/carvel_dev/status/1408147318235447298?s=20

Thank you!

**Comment by adriens** [comment]
😆  thanks a lot @microwavables  😗 
https://twitter.com/rastadidi/status/1408151191993798656
