### ISSUE TITLE
🎁 Write a post of a vendir usecase 🎁 

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#83]
# Context

`vendir` 's features allow a lot of things, not only around kubernertes. It could be interesting to show how `vendir` can make things easier, and to make package software installation even smoother.

# Action

- Show how `vendir` can make APOC plugin installation easier in Neo4J (shox how to move away manual tasks)

**Comment by adriens** [comment]
✅ Done 

- [x] [DEV.to post](https://dev.to/adriens/deploy-neo4j-s-apoc-plugin-with-code-thanks-to-carvel-vendir-33l4)
- [x] [Tweet](https://twitter.com/rastadidi/status/1411864443567312907)
- [x] [linkedIn Post](https://www.linkedin.com/posts/adrien-sales_deploy-neo4js-apoc-plugin-with-code-thanks-activity-6817632342102962176-KwAj)

**Comment by ewrenn8** [comment]
I just gave it a read, thanks for writing up a great post @adriens!

**Comment by adriens** [comment]
You're very wlecome, thanks a lot for the tool 👏 

BTW, I'm ready to transfer repo ownership, just let me know when you'd like me to perform the action
