### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by WnP** [carvel-dev/vendir#88]
**Describe the problem/challenge you have**
We are using quite a lot [mercurial SMC](https://www.mercurial-scm.org/) and it would awesome to be able to clone our projects using vendir.

**Describe the solution you'd like**
It should be less or more a copy of git.go.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
@WnP im in favor of this. would you be interested in contributing support for this?

**Comment by WnP** [comment]
Hi @cppforlife,

Here is a simple mecurial - hg - implementation. feedback welcome!

**Comment by WnP** [comment]
I guess we should remove the `.hg` folder - because it contains some sensitive information inside `.hg/hgrc`, like the authentication password.

it looks like it's done for the `.git` folder but I didn't see where in the code base.

**Comment by cppforlife** [comment]
> it looks like it's done for the .git folder but I didn't see where in the code base.

https://github.com/vmware-tanzu/carvel-vendir/blob/develop/pkg/vendir/fetch/git/git.go#L81-L86

**Comment by WnP** [comment]
@cppforlife this remove the `authDir` which is something like `$PWD/.vendir-tmp/incoming/git-auth`, not the `$PWD/target/repo/path/.git` folder :thinking: 

I've preserved this, but for mercurial I need to store the password as plain text in `.hg/hgrc`, it cannot be retrieved from another location - at least as far as I know.

**Comment by WnP** [comment]
Maybe I should just remove it after fetching the repo, by the way we this can be done using `includePaths`. I not sure what should be done here.

**Comment by WnP** [comment]
Well, I've found a way to pass the password using CLI arguments. I think it's a better approach.

Let me know your thoughts.

**Comment by cppforlife** [comment]
not ideal to pass them as args since they will be visible in process tree. it seems that there is an env var HGRCPATH (https://stackoverflow.com/questions/12185048/mercurial-hg-pull-parameters-username-and-password/12187000#12187000).

**Comment by WnP** [comment]
@cppforlife nice catch, I didn't know about this one. Let me refactor my code and update the pull request.

**Comment by WnP** [comment]
@cppforlife I've published my changes.

Let me know your thoughts

**Comment by WnP** [comment]
@cppforlife I've finish my changes on #91, I think everything is OK now.

Let me know if you want more changes.
