### ISSUE TITLE
release asset size error (due to 404 during asset download)

### ISSUE THREAD

**Issue by benhass** [carvel-dev/vendir#9]
I'm seeing an issue where vendir throws an error when checking the release asset file size: `Checking asset 'file.txt' size: Expected file size to be 74, but was 9`. I checked the api response for release assets, it shows the asset size is 74 bytes. When I manually download the file, it is 74 bytes. Any idea what would cause this?

Some details from the API response (some parts are omitted or renamed):

```
[
  {
    "name": "file.txt",
    "label": "",
    "content_type": "application/text",
    "state": "uploaded",
    "size": 74,
    "download_count": 5,
    "created_at": "2020-08-04T19:58:28Z",
    "updated_at": "2020-08-04T19:58:29Z",
    "browser_download_url": "https://github.com/org/repo/releases/download/v3/file.txt"
  }
]
```

**Comment by cppforlife** [comment]
hmm, interesting. here is the code: https://github.com/k14s/vendir/blob/7e9c900d438eac21867e24be007411e7ba1fc156/pkg/vendir/directory/github_release_sync.go#L74-L82

it downloads and then checks size. i wonder if there is some http error being returned because downloadFile isnt checking for 200 status. you might be hitting github rate limit error: https://github.com/k14s/vendir/blob/develop/docs/github-release.md#github-api-rate-limiting ?

**Comment by benhass** [comment]
Thanks for looking into this @cppforlife. I am using a personal access token since this repo is private, so I think it would be pretty unlikely that I hit a rate limit. I also haven't seen any issues at all when requesting the file directly via browser or wget request with the token.

**Comment by benhass** [comment]
I added a conditional in there to throw an error if the response is non-200 and it looks like I'm getting a 404 for the asset download. Have you confirmed that this works for private repos? I wish I could share more info with you to help troubleshoot...

**Comment by benhass** [comment]
I used this handy script for sanity checking https://gist.github.com/josh-padnick/fdae42c07e648c798fc27dec2367da21

**Comment by cppforlife** [comment]
hmm, looks like github asset download url didnt work for private repos. switching to asset resource url + header does seem to work. fixed in https://github.com/k14s/vendir/commit/47d346d0536988ab569e7411203a4c97f7c71000. will cut release right after CI passes.

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/vendir/releases/tag/v0.9.0

**Comment by benhass** [comment]
Thanks so much for the quick fix! This is working for me now.
