### ISSUE TITLE
Support Multiple Secrets

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/vendir#93]
**Describe the problem/challenge you have**
We likely need to support multiple secrets as part of the packaging / secretgen / package repository auth work. 

The code at : https://github.com/vmware-tanzu/carvel-vendir/blob/develop/pkg/vendir/fetch/imgpkgbundle/sync.go#L83
assumes only one secret.

**Describe the solution you'd like**
vendir is able to pass down multiple registry authentication credentials to imgpkg

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Thank you for surfacing this. I'm moving this to the top of the backlog since it's a blocker for the private registry authentication work.

**Comment by cppforlife** [comment]
included in https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.22.0
