### ISSUE TITLE
🐦 Please Tweet about the v0.22.0 🐦 

### ISSUE THREAD

**Issue by adriens** [carvel-dev/vendir#98]
Hi guys, could you please send a tweet about the [v0.22.0](https://github.com/vmware-tanzu/carvel-vendir/releases/tag/v0.22.0) release so I'll can retweet it ?

Thank you in advance for your help 🙏 
Have a great week.
Adrien

**Comment by cppforlife** [comment]
sorry, thats my bad. didnt notify @microwavables about the release.

**Comment by adriens** [comment]
No worry @cppforlife , let's stay relax about that 😸 💟

**Comment by microwavables** [comment]
Here ya go! https://twitter.com/carvel_dev/status/1428485539607597063?s=20

**Comment by adriens** [comment]
Yep 🚀 https://twitter.com/rastadidi/status/1428489292528046083
